# Cloudflare Pages configuration for Math Learning Adventure
name = "mathahorn"
compatibility_date = "2024-01-15"

[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

# Environment variables (set these in Cloudflare Pages dashboard)
[vars]
  ENVIRONMENT = "production"
  CUSTOM_KEY = "production"

# Headers for security and performance
[[headers]]
pattern = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "strict-origin-when-cross-origin"
  
# Cache static assets
[[headers]]
pattern = "/static/*"
[headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
pattern = "/_next/static/*"
[headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
pattern = "*.png"
[headers.values]
  Cache-Control = "public, max-age=31536000"

[[headers]]
pattern = "*.jpg"
[headers.values]
  Cache-Control = "public, max-age=31536000"

[[headers]]
pattern = "*.svg"
[headers.values]
  Cache-Control = "public, max-age=31536000"

# Redirects for SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200